import { Score } from './enums';
import { Levels, Technologies } from './enums/filters.enum';
import { InterviewQuestion } from './interfaces/interview.interface';

export const questions: InterviewQuestion[] = [
  {
    level: Levels.Beginner,
    question: 'What is Angular ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is component in theory?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What and why could use Angular CLI ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'How to declare component ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is selector ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'Examples of non-elemental selectors?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is template? Which ways to define template ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is styles ? Which ways to define styles?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the changeDetection?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the changeDetection strategy? What is difference between them ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the preferred change detection strategy ? Why ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is the viewProviders ? Example of use cases',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is the moduleId for component ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the animations ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is the interpolation within component decorator ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is the preserveWhitespaces within component decorator ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },

  /* Angular Animations Questions  */

  {
    level: Levels.Intermediate,
    question: 'How works the changeDetection property for the component ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  /* Component Decorator settings questions */
  {
    level: Levels.Beginner,
    question: 'What is component lifecycle ? ',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'How to respond to lifecycle events ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'Lifecycle events sequence ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What should be done within ngOnInit ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What should be done within ngOnDestroy ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What should be done within ngOnChanges ? Examples of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What should be used for custom change detection ? Use cases for custom change detection ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What should be done within AfterContentInit and AfterContentChecked ? Example of use cases ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What should be done within AfterViewInit and AfterViewChecked ? Example of use cases ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the difference between Init and Checked for View and Content lifecycle methods',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'View Encapsulation',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'View Encapsulation modes',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'Difference between ShadowDom and Emulated modes',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'Downsides and Upsides for Encapsulation = None mode',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is Shadow DOM',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.DOM,
  },
  {
    level: Levels.Advanced,
    question: 'What is the examples of usages ShadowDOM directly? Upsides and downsides ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.DOM,
  },
  {
    level: Levels.Advanced,
    question: 'What is the VirtualDOM ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.DOM,
  },
  {
    level: Levels.Advanced,
    question: 'What is the difference between ShadowDOM and VirtualDOM ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.DOM,
  },
  {
    level: Levels.Beginner,
    question: 'What is component interactions. What is default approaches ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is Input decorator ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'Can we parametrize input decorators ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'Renaming the input parameter is a good approach ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'How we can intercept the input changes?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is Output decorator ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is EventEmitter ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is EventEmitter under the hood ? Could we use this class somewhere else ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is locale template variable ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the type of template variable? Can we read that reference by a different type?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'How we can use template variable? How and when we can assign or pass template variable',
    hint: 'exportAs, ngTemplateOutletContext',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is ngTemplateOutlet ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is $implicit means withing ngTemplateOutlet context? Do/How we can use this ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is $implicit means withing ngTemplateOutlet context? Do/How we can use this ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is ngTemplateOutletContext means for ngTemplateOutlet context? Examples of usages ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'How we can improve typechecking for templates?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'The ngTemplateContextGuard usage ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'The ngTemplateGuard_(someInputProperty) usage ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is the ViewChild ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What we can use as ViewChild selector ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How we can configure ViewChild?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the purpose for the static property (ViewChild/ContentChild context)?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the ViewChildren ? What the difference between ViewChildren and ViewChild ? ',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is the ContentChild ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How we can configure ContentChild ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the return model for ViewChildren/ContentChildren queries?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is read property configure for view/content queries ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is descendants property configure for ContentChildren ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the ContentChildren ? What the difference between ContentChild and ContentChildren ? ',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the difference between ViewChild and ContentChild ? ',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is the static/dynamic queries in scope of view/content queries ? ',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'Why we cant configure static property for the ViewChildren/ContentChildren ? ',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'How components could interact with each other by service ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  // Styling of components
  {
    level: Levels.Beginner,
    question: 'What is the default style scope for component ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What the :host selector for the component? Why we could use it ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is :host-context selector for the component?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is the difference between the :host-context and :host ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is ::ng-deep ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is downsides and upsides of ::ng-deep ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How to mitigate default ::ng-deep behaviour which makes all styles global ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'Do we need to use ::ng-deep for Encapsulation = None mode ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What the types of importing styles we could use for a component ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the preferred way to declare the styles for the component ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'Can we use multiple files for styling one component ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is content projection ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is single-slot projection ? How to implement ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is multi-slot projection ? How to implement ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is conditional content projection ? How to implement ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question:
      'Why we should use ng-template instead of ng-content for conditional content projection ? Do we still can implement conditional rendering by ng-content ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is the upsides of ng-template over ng-content for conditional content projection ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is the upsides of ng-template over ng-content for conditional content projection ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is ViewContainerRef ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is example of usages for ViewContainerRef ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is ngProjectAs ? Example of usage ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is dynamic component ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is ComponentFactoryResolver ? Example of usages ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is Angular Elements ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is Custom Elements ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.DOM,
  },
  // Custom Angular Elements questions
  {
    level: Levels.Beginner,
    question: 'What is template for component?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },

  {
    level: Levels.Beginner,
    question: 'What is text interpolation ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is template expressions ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is the template statements ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is supported syntax for the template ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'Why we cant use all JavaScript features within template ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is the template context ? What we could be used at template ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the best practices for the template expressions ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the best practices for the template statements ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is the pipe ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What are the default built-in pipes?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is the pipe operator ? Where we can use pipes ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is the pipe chaining ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'How to create a custom pipe ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'When and why pipe will be recalculated ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is pure pipe ? Examples',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is impure pipe ? Examples',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is difference between impure and pure pipes ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is pipe precedence ? Example of pitfalls',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is property binding ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What and how property process binding ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What and how we can bind by using property binding ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What the security measures applied for binding values ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the attribute binding ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'When we should use attribute binding ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How to use class binding ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How to bind multiple classes ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How to bind style attribute ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is the styling precedence ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is styles delegation with lower precedence ? Examples of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is styles delegation with lower precedence ? Examples of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'How to take attribute value from the Directive/Component ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is the downsides of Attribute decorator ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is event binding ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'Which events we can bind ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'How to bind custom events ? Example',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is $event object ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is passive event listener ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.JavaScript,
  },
  {
    level: Levels.Advanced,
    question: 'What is upsides for passive event listeners ? Example of usages ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.JavaScript,
  },
  {
    level: Levels.Advanced,
    question: 'How to enable passive event listeners for Angular app ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.JavaScript,
  },
  {
    level: Levels.Beginner,
    question: 'What is two-way data binding ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How is two-way data binding works under the hood ? Example ',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How to implement custom two-way data binding ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is main purpose for the template variable ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What we can access by template variable ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is the visibility scope for template variable ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is template input variable ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is difference between template and template input variables ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  // SVG as templates
  {
    level: Levels.Beginner,
    question: 'What is directive ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is available types of directives ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is attribute directive ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is most common attribute directives ?',
    hint: 'NgClass, NgStyle',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is NgClass ? How it works ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is NgStyle ? How it works ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is difference between NgStyle and NgClass ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is structural directive ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is most common structural directives ?',
    hint: 'NgIf, NgFor',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is NgIf ? How it works ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How to customize NgIf ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is ng-container ? Example of usages ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'How to create custom NgIf directive ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is NgFor ? How it works ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How to configure NgFor',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is potential downsides for NgFor ? How to fix that downsides ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'How to create custom NgFor ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is NgSwitch ? How it works ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is NgSwitchDefault ? How it works ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is difference between structural and attribute directive ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'Can we use multiple attribute directives on one host ? What the execution order ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'Can we use multiple structural directives on one host ? What is pitfalls ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'How to create custom attribute directive ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'How to implement attribute directive functionalities ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is the HostBinding ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is the HostListener ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How to listen global events by the HostListener ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'How to take event object from the HostListener ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'How to pass input parameters to directive ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How to pass input parameter directly into directive without additional input binding ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    hint: 'Input name should be matched to the directive name',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is NgNonBindable ? How it works ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is NgNonBindable use cases ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How to create custom structural directive ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How to provide custom input properties for structural directive ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What means * in template syntax for structural directive ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'Do we can implement structural directive functionality without * in template ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is structural directive syntax ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'How to implement type guards for structural directive ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is dependency injection ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is dependency injection in theory ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.JavaScript,
  },
  {
    level: Levels.Beginner,
    question: 'What is the service ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is the best practices for define the service ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the injectable service ? What is the difference between service ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    hint: 'We not required to use Injectable decorator',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'How to define provider scope for the service ? Do we need to register service ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is providedIn property at Injectable decorator ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is another options for providedIn property ? What is use cases for them ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'How to inject service ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is DI token ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is could be as the DI token ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is DI in programming ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.JavaScript,
  },
  {
    level: Levels.Beginner,
    question: 'What is providers property ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    hint: 'NgModule',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'How to define providers ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is available provider options ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is available provider options ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is useValue as provider option ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is useExisting as provider option ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is useClass as provider option ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is useFactory as provider option ? Example of usages',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is the main differences between useFactory/useClass/useExisting as provider option ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is the InjectionToken?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'Why to use InjectionToken? Examples of use cases ',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is provider aliasing ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'How to provide class alias ? Example of use cases ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'How to provide multiple aliases ? Example of use cases ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the default typing for injection tokens ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'Do we can use interface as injection tokens ? Why ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is deps as provider option ? Example of usages?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the Inject decorator ? Example of use cases ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is the Injector decorator ? Example of use cases',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is the NgModule ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is the main purpose of NgModule ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is included into NgModule metadata ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is providers in scope of NgModule ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is declarations in scope of NgModule ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What should be placed into declarations and what shouldnt ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is imports in scope of NgModule ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What should be placed into imports and what shouldnt ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is bootstrap in scope of NgModule ? What should be placed here  ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is exports in scope of NgModule ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What should be placed into exports and what shouldnt ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'How bootstrap working under the hood ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'How we can customize bootstrap logic ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'Do we can use multiple components for bootstrap ? How it will be work ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is frequently-used Angular modules ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the difference between NgModule and JS Module ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the NgModule category ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is the list of NgModule categories ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  // Advances. NgModule Categories
  {
    level: Levels.Beginner,
    question: 'What is routing module ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is sharing modules ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is root/feature modules ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is root/feature modules ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is eager/lazy-loading modules ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is provider scope for the eager module ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is difference between eager/lazy-loading module ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'Why lazy-loading module creates own child injector ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is provider scope for the lazy-loaded module ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'How to limit provider scope ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    hint: 'Components',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'What is injector hierarchy ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is singleton service ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is singleton in theory ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.JavaScript,
  },
  {
    level: Levels.Beginner,
    question: 'How to provide singleton service ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is forRoot/forChild pattern ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'How to prevent module reimport ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'Do the provider from feature module will be accessible from the whole app ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Intermediate,
    question: 'Do the provider from lazy-loaded module will be accessible from the whole app ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'Why shared module shouldnt have an providers ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is entry component?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'Why entry component exist as concept ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is difference between entry component and bootstrap component?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Advanced,
    question: 'What is Angular compiler? How it works ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  {
    level: Levels.Beginner,
    question: 'What is RxJS ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'What is Observable ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'Do the observables asynchronous ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Intermediate,
    question: 'What is Observer pattern ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.JavaScript,
  },
  {
    level: Levels.Advanced,
    question: 'What is Producer / Consumer?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'What is the subscribe purpose for Observable?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'What is the Subscription ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'What is the Observer ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    hint: 'next,error,complete',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'How to create an observable ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'What mean the next method for the observer ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'What mean the complete method for the observer ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Intermediate,
    question: 'What the difference between complete and next ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'What the cold observable ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'What the hot observable ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Intermediate,
    question: 'How to make observable hot ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'Do the observables unicast or multicast by default ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'How unicast works ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Intermediate,
    question: 'What is multicasting ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Intermediate,
    question: 'What is difference between unicast and multicast ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'How to handle errors ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'What is operator ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Beginner,
    question: 'What is common operators ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  // Questions according to different area operators for intermediate
  {
    level: Levels.Beginner,
    question: 'How Angular uses observables ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    hint: 'EventEmitter, Router, Http',
    technology: Technologies.RxJS,
  },
  {
    level: Levels.Intermediate,
    question: 'What the difference between Promise and Observable ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.RxJS,
  },
  //  Questions according to comparisons between different approaches
  {
    level: Levels.Beginner,
    question: 'What the Angular Routing?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  // Questions according to Routing
  {
    level: Levels.Beginner,
    question: 'What the Angular Forms?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  // Questions according to Forms
  {
    level: Levels.Beginner,
    question: 'What Angular uses for communication with backed services ?',
    practiceScore: Score.NotFamiliar,
    knowledgeScore: Score.NotFamiliar,
    note: '',
    technology: Technologies.Angular,
  },
  // Questions according to HTTP
];
